# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build, test, release

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-test-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Set up Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version: "1.25.5"

      - name: Build
        run: go build -o bin/indev cmd/indev/main.go

      - name: Test
        run: go test ./...

      - name: Generate GitHub app token for Homebrew Tap App
        id: generate-app-token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        with:
          app-id: ${{ vars.HOMEBREW_TAP_APP_ID }}
          private-key: ${{ secrets.HOMEBREW_TAP_APP_PRIVATE_KEY }}
          owner: intility
          repositories: homebrew-tap

      - name: GoReleaser Action
        uses: goreleaser/goreleaser-action@5742e2a039330cbb23ebf35f046f814d4c6ff811 # v5.1.0
        with:
          args: release --clean
          version: 2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAP_REPO_GITHUB_TOKEN: ${{ steps.generate-app-token.outputs.token }}
          DOWNLOADER_GITHUB_TOKEN: ${{ secrets.DOWNLOADER_GITHUB_TOKEN }}
          OTLP_ENDPOINT: ${{ vars.OTLP_ENDPOINT }}
          OTLP_TOKEN: ${{ vars.OLTP_TOKEN }}
          SENTRY_DSN: ${{ vars.SENTRY_DSN }}
          AUTH_AUDIENCE: ${{ vars.AUTH_AUDIENCE }}
          AUTH_AUTHORITY: ${{ vars.AUTH_AUTHORITY }}
          AUTH_CLIENT_ID: ${{ vars.AUTH_CLIENT_ID }}
          AUTH_REDIRECT_URI: ${{ vars.AUTH_REDIRECT_URI }}
          PLATFORM_BASE_URI: ${{ vars.PLATFORM_BASE_URI }}
